services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    container_name: rsoket_db
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: