services:
  server1:
    build: .
    ports:
      - 8081:8080
    container_name: rksp5web1
  server2:
    build: .
    ports:
      - 8082:8080
    container_name: rksp5web2
  server3:
    build: .
    ports:
      - 8083:8080
    container_name: rksp5web3
  server4:
    build: .
    ports:
      - 8084:8080
    container_name: rksp5web4
  balancer:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: rksp5balancer

# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' rksp5web1
